# Generated by Django 5.1.1 on 2024-09-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_product_subcategory_category_parent_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('html_text', models.TextField()),
                ('simple_text', models.TextField(blank=True, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
