# Generated by Django 5.1.1 on 2024-09-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_scrapedpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapedpage',
            old_name='html_text',
            new_name='html_content',
        ),
        migrations.RenameField(
            model_name='scrapedpage',
            old_name='simple_text',
            new_name='plain_text',
        ),
    ]
