# Generated by Django 5.1.1 on 2024-09-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_html_text_scrapedpage_html_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=255)),
                ('date_posted', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapedPage',
        ),
    ]
