# Generated by Django 5.1.1 on 2024-10-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_job_delete_scrapedpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='catagory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
