# Generated by Django 5.1.1 on 2024-10-03 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_job_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='catagory',
            new_name='platform',
        ),
        migrations.AddField(
            model_name='job',
            name='already_exist_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='company_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_url_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='email_validated',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='invalid_title_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='job_fetch_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='lead_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='lead_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_date_formatted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='validated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
