# Generated by Django 5.1.1 on 2024-10-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_catagory_job_platform_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Jobs',
        ),
    ]
