# Generated by Django 5.1.1 on 2024-10-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_jobs_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=100)),
                ('date_posted', models.DateField()),
                ('lead_url', models.URLField()),
                ('platform', models.CharField(default='Indeed', max_length=100)),
            ],
        ),
    ]
