# Generated by Django 5.1.1 on 2024-10-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_scrapedjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapedJob',
        ),
    ]
