# Generated by Django 5.1.1 on 2024-10-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
