# Generated by Django 5.1.1 on 2024-10-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_job_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
