# Generated by Django 5.1.1 on 2024-10-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
