# Generated by Django 5.1.1 on 2024-10-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
