# Generated by Django 5.1.1 on 2024-10-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_job_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.IntegerField(default=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
