# Generated by Django 5.1.1 on 2024-10-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_job_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
