# Generated by Django 5.1.1 on 2024-10-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_job_id_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
